[package]
name = "lua-bundle"
readme = "README.md"
description = "a lua file concatter"
repository = "https://codeberg.org/lua-tools/lua-bundle"

license = "GPL-3.0-only"
version = "0.1.3"
edition = "2024"

[[bin]]
name = "lua-bundle"
path = "src/bin/bundle/main.rs"

[dependencies]
clap = {version = "4.6.0", features = ["derive"] }
toml = "1.1.2"
