[package]
name = "lua-bundle"
readme = "README.md"
description = "a lua file concatter"
repository = "https://github.com/lua-tools/lua-bundle"

license = "GPL-3.0-only"
version = "0.1.2"
edition = "2024"

[[bin]]
name = "lua-bundle"
path = "src/bin/bundle/main.rs"

[dependencies]
toml = "0.9.7"
